# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Jinka Venkata Sai Kiran
title: Software Engineer and Content Writer 
email: kiranjv888@outlook.com
website: http://bit.ly/4afV3Ob 

# Social links
twitter_username: saikiranjv
github_username:  kiranjv888
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: sai-kiran-jv-028609a2
# pinterest_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Senior Software Engineer with 10 years of experience in distributed systems, DBMS kernel development, Open Table Formats (Iceberg/Delta), cloud integration, IoT systems, and AI-driven automation. Strong expertise in C/C++, Metadata engines, Parquet readers, NOS integration, and Agentic AI workflows leveraging RAG to enhance engineering intelligence. Proven ability to design large-scale data-platform components, lead modules, and deliver high-performance features.

# Experience Section
# experience_title: Experience

# Projects Section
# projects_title: Projects

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Jogging
   - Playing Cricket & Football
   - Reading Books & Analysing Business
   - Blogging

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
